#ifndef _H_BIBERBUT_BARAKA_H_
#define _H_BIBERBUT_BARAKA_H_


#include "TDRV2605.h"
#include "TMAVPARAMS.h"
#include "app.h"
#include "SYSBIOS.H"
#include "TJOYSTICK.h"


//enum EVIBRMOD {EVIBRMOD_AUTO = EJSTCPINS_B3, EVIBRMOD_STAB = EJSTCPINS_B4, EVIBRMOD_RTL = EJSTCPINS_B5, EVIBRMOD_MIN = EJSTCPINS_B2, EVIBRMOD_MAX = EJSTCPINS_B1, EVIBRMOD_ARM = EJSTCPINS_B8, EVIBRMOD_CHUTE = EJSTCPINS_B7, EVIBRMOD_BANO = EJSTCPINS_B6, EVIBRMOD_ENDENUM = 8};
enum EVIBRKEY {EVIBRKEY_AUTO = 0, EVIBRKEY_STAB, EVIBRKEY_RTL, EVIBRKEY_MIN , EVIBRKEY_MAX , EVIBRKEY_ARM , EVIBRKEY_CHUTE, EVIBRKEY_BANO, EVIBRKEY_ENDENUM = 8};

class TBIBERBUT {
		TDRV2605 *vibr;
		TMAVPARAMS *param;
	
		uint8_t butonmode[EVIBRKEY_ENDENUM];

	public:
		TBIBERBUT (TDRV2605 *vbr, TMAVPARAMS *prm);
		void vibro (EVIBRKEY m);
};



#endif
